sudo: required
language: node_js
node_js:
- '8'
before_install:
- gem install sass
- gem install scss_lint
- npm install -g npm
before_script:
- npm i
script:
- npm run prod
- npm run test
