version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: sudo npm install -g npm
      - run: sudo npm i
      - run: sudo npm run prod
      - run: sudo npm test
      - run: sudo npm workbox
